## This helper function can be used to generate moving-average (MA) series
#  based on the chosen parameters: MA type and lag length.
#  The output in the form of MA series can then be used along with
#  price quotations to generate trading signals.
#  Note:
#  - for lag length equal to 1, we simply copy the original vector,
#  - we replace leading MA NAs with 0’s as this is exactly the starting
#    all-cash position that earns risk-free return until a trading
#    signal can be generated by the generate_trades() C++ function,
#  . calculation of intraday MAs is delegated to that same C++ function.


s_calculate_ma <- function(vec, ma_type, ma_lag) {
  
  if (ma_lag == 1) {
    vec
  } else {
    do.call(ma_type, list(vec, n = ma_lag)) %>%
      replace_na(0)  # replace leading lag NAs with 0’s
  }
    
}
